/**
 * The homepage atmosphere progression — the tonal ground as a pure function of scroll position.
 *
 * Two requirements make this a module rather than some CSS, and both are things a browser cannot
 * check cheaply:
 *
 *  - **FR-015 / SC-004** — "no meaningful text falls below its legibility threshold at any intermediate
 *    point — zero failing measurements, not an average." A progression can pass at every stage and fail
 *    between two of them, and only while the page is moving.
 *  - **FR-007** — the tone must be exactly right at any entry position, including the top and the
 *    bottom, after a reload, after back/forward, and after an end-key jump.
 *
 * Both are properties of a function, so they are asserted in
 * `tests/unit/atmosphere-progression.test.ts` over a 500-step sweep, and the browser only has to
 * confirm the function is wired to the pixels.
 *
 * **No DOM here.** Layout numbers come in as arguments; nothing reads `window`. That keeps this in the
 * existing node-environment test harness — research.md D6 refuses a DOM harness, and a module that
 * touches the document could not be tested at all.
 *
 * The direction is deliberate and it is the whole point of the feature: the page today alternates
 * light left, light right, light left (`app/globals.css:193-214`), which is why it reads busy. This
 * progression moves one way only — a steady descent from the warm opening at the hero into the deepest
 * oxblood at the closing call to action. FR-003 asks for "a single deliberate sequence with a clear
 * overall direction"; the monotonicity assertion in the test is what stops it decaying back into an
 * alternation.
 */

/**
 * The anchors the ground travels between, in document order.
 *
 * The input to this list is the **rendered DOM**, not a hand-maintained record: the drift guard in
 * `tests/unit/atmosphere-progression.test.ts` compares it against the section ids captured from the live
 * page (`specs/001-premium-rtl-storefront/baseline/manifest-after.json`, regenerated by
 * `verification/capture-baseline.mjs`). An entry that stops existing, or a section that appears here
 * late, fails that guard rather than silently flattening the tour.
 *
 * Feature 007 changed this list once already: `trust` and `final-conversion` are gone because the
 * assembly band replaces those two sections plus the store-experience section with **one** `<section
 * id="store-experience">` carrying three statements, and the closing anchor moved onto a `div` inside
 * that band. The id survives on the band rather than being renamed so that three existing consumers keep
 * resolving with no edit: the `counter` stage below, `components/layout/Footer.tsx`'s «درباره ما», and
 * `mobileQuickRoutes`.
 */
export const HOMEPAGE_SECTIONS = [
  "top",
  "featured",
  "categories",
  "brands",
  "new-arrivals",
  "b2b",
  "online-services",
  "store-experience",
  "band-settled",
] as const;

/**
 * Anchors that live **inside** a section instead of being one.
 *
 * `band-settled` is a `div` at the end of the assembly band's pinned track (feature 007), so the ground
 * can measure it — `getElementById` does not care about the tag — but the drift guard's DOM capture
 * queries `section` elements and will never see it. Without this exemption the guard reads 9 declared
 * anchors against 8 rendered sections and goes red on a page that is correct, which is the failure mode
 * that makes people weaken a guard instead of fixing its arithmetic.
 *
 * It is a separate list rather than a special case in the comparison so that adding an in-section anchor
 * stays a deliberate edit to this file.
 */
export const SUBTREE_ANCHORS = ["band-settled"] as const;

/**
 * Sections that render on the homepage and deliberately carry no ground stage.
 *
 * This list exists because the drift guard used to compare `HOMEPAGE_SECTIONS` against a JSON record
 * captured at T001 — a file anyone editing the page can also edit, which is what I did on 2026-09-24 when
 * the accessories chapter came out. The guard passed by construction, so it was not a guard. It now reads
 * the section list off the **rendered DOM** (`baseline/manifest-after.json`, regenerated at each
 * checkpoint), and every rendered section must be either an anchor above or named here. `obtainable-now`
 * sits between the hero and the featured rail and is short enough that no stage boundary wants to live
 * inside it; if that changes, move it to `HOMEPAGE_SECTIONS` rather than deleting it from this list.
 */
export const UNANCHORED_SECTIONS = ["obtainable-now"] as const;

export type SectionAnchor = (typeof HOMEPAGE_SECTIONS)[number];

export type AtmosphereStage = {
  readonly key: string;
  readonly anchor: SectionAnchor;
  /** `#rrggbb`. Compared and interpolated as text, so the exact case is not load-bearing. */
  readonly color: string;
};

/**
 * Six stages, and they travel — this is the second attempt at this array, and the first one's failure is
 * the reason it is shaped this way.
 *
 * The original four (`#2A0409 → #1C0206 → #130104 → #0D0205`) satisfied every assertion the feature
 * shipped with and produced a ground the owner described as "the same colour all along". They were right,
 * and the measurement agrees: sampled at the gutter pixel down the live page the sequence runs
 * `#1D0308 → #150105 → #110104 → #0E0103 → #0C0002 → #0B0003 → #0B0104`, so the back half of a 16,384px
 * document moves by three units in one channel. In CIE terms the four legs are ΔE 9.8 / 4.6 / 2.6 — the
 * last two are below the ~10 at which a change is noticeable at all, and all four sit in the same hue
 * (`14° → 358°`) while chroma collapses 19.6 → 3.4. It was not a progression through rooms; it was one
 * colour switching itself off.
 *
 * So depth alone is not what FR-003's "clear overall direction" can be satisfied by, and the direction
 * this array carries is a **tour that closes**: warmth → wine → ink at the trade chapter → back to an
 * ember at the physical store → the deepest tone on the page at the closing call. The luminance range is
 * deliberately narrow (`Y` 0.0027–0.0121, inside `LEGIBILITY_BAND` at every interpolated point) because
 * the travel is carried by **hue and chroma**, which cost contrast nothing. That is the whole trick of
 * moving a dark ground: lightness is the one axis that cannot be used freely.
 *
 * Since feature 007 the last leg — ember to closing dark — runs **inside the assembly band**, from the
 * stack beat to the lock beat. The ground is a function of scroll and never of time, so the tone keeps
 * travelling while the band's shell is pinned and its content is not; that is the authored behaviour, not
 * the lag feature 002 forbids.
 *
 * Six stages, not the "three or four closely-related stages" 002's coherence assumption asked for: that
 * sentence was written about a descent, and a descent of six steps is exactly the alternation it warns
 * against. Amended 2026-09-23 (002 Amendment Record #4) — the guard is no longer "few stages, one axis",
 * it is "every leg perceptible, no leg retraced", which is asserted in the unit sweep.
 *
 * Two stops are not invented: `#3A0C12` opens at the tone the hero gutter already measures
 * (`#3d0912 → #3f0912` in the baseline), and `#160406` keeps the closing chapter the darkest on the page.
 * The deepest tone stays above the sRGB linear-branch knee on at least one channel — `0.04045`, which is
 * byte 10 — for the same reason the first array learned about: below it, luminance collapses to under the
 * band floor and the ground reads as an unstyled page rather than a deep one.
 */
export const PROGRESSION = [
  { key: "arrival", anchor: "top", color: "#3A0C12" },
  { key: "goods", anchor: "categories", color: "#2A0713" },
  { key: "shelves", anchor: "brands", color: "#1A0A16" },
  { key: "trade", anchor: "b2b", color: "#0E1122" },
  { key: "counter", anchor: "store-experience", color: "#320B0A" },
  { key: "close", anchor: "band-settled", color: "#160406" },
] as const satisfies readonly AtmosphereStage[];

/**
 * The band every tone — stage or interpolated — must stay inside.
 *
 * `max` is the binding edge: the ground is behind light text, so a lighter ground is the only way this
 * layer can make the page harder to read. 0.0200 relative luminance still leaves the dimmest declared
 * text above 5:1. `min` exists so the descent cannot collapse into flat black, which would erase the
 * glows this feature is layered over and read as an unstyled page rather than a deep one.
 */
export const LEGIBILITY_BAND = { min: 0.001, max: 0.02 } as const;

/**
 * Opaque stand-ins for the text actually rendered on the homepage, composited by hand against the
 * darkest plausible ground so the alpha is not doing the arithmetic for us.
 *
 * `foreground/50` and anything dimmer is deliberately absent: those are used on the light "paper"
 * chapter's own surfaces, not on the atmosphere ground, and pretending otherwise would let a real
 * failure hide behind an over-strict list.
 */
export const SCENE_TEXT_COLOURS = {
  heading: "#F0ECE9",
  body: "#E8E3E0",
  muted: "#B9B3B0",
  meta: "#9A938F",
  champagne: "#E5D3B3",
  champagneDeep: "#C5A880",
} as const;

/** The tone used when the effect cannot run — FR-024 forbids an unstyled default. */
export const FALLBACK_TONE = PROGRESSION[0].color;

const clamp01 = (value: number) => (Number.isFinite(value) ? Math.min(1, Math.max(0, value)) : 0);

const toRgb = (hex: string): readonly [number, number, number] => {
  const value = hex.replace("#", "");
  return [
    Number.parseInt(value.slice(0, 2), 16),
    Number.parseInt(value.slice(2, 4), 16),
    Number.parseInt(value.slice(4, 6), 16),
  ];
};

const toHex = (r: number, g: number, b: number) =>
  `#${[r, g, b].map((v) => Math.round(Math.min(255, Math.max(0, v))).toString(16).padStart(2, "0")).join("")}`;

const channelLuminance = (byte: number) => {
  const c = byte / 255;
  return c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4;
};

export function luminanceOf(hex: string): number {
  const [r, g, b] = toRgb(hex);
  return 0.2126 * channelLuminance(r) + 0.7152 * channelLuminance(g) + 0.0722 * channelLuminance(b);
}

/** WCAG 2.x contrast ratio between a text colour and the ground behind it. */
export function contrastOn(text: string, ground: string): number {
  const a = luminanceOf(text);
  const b = luminanceOf(ground);
  const [higher, lower] = a > b ? [a, b] : [b, a];
  return (higher + 0.05) / (lower + 0.05);
}

/**
 * The interior shopper pages — owner decision 5: "extend the atmosphere to every shopper page".
 *
 * Extending it is not the same as extending *the tour*. FR-001 binds the homepage ("The homepage page
 * ground MUST change across the length of the page"), and the six stages are anchored to eleven homepage
 * sections that a listing page does not have. Running the tour on `/shop` would spread six chapters across
 * a 4,547px document that has three visual events in it, and FR-002 — the shift must read as belonging to
 * the page's structure — would be violated by construction: the ground would be moving where nothing moves.
 *
 * So an interior page gets **one settled tone, borrowed from the homepage chapter it belongs to.** Every
 * browse route — the listing, a product page, a category, a brand — takes the goods tone, because prefix
 * matching cannot tell `/shop` from `/shop/گوشی-…` without learning the route table, and a product page is
 * the same kind of room as the listing that led to it. The checkout takes the closing dark, the account
 * family the deep neutral, the B2B form the ink of the trade chapter. The atmosphere is therefore
 * continuous across the site without pretending every page is a journey, and the colour a shopper sees on a
 * route is a statement about what that route is for.
 *
 * No scroll listener, no rAF, no measurement: a static layer. The listing page in particular used to pay
 * for eleven `getElementById` reads on mount to place stages that could not be felt.
 */
export const INTERIOR_GROUNDS = {
  "/shop": "#2A0713",
  "/categories": "#2A0713",
  "/brands": "#2A0713",
  "/cart": "#220708",
  "/checkout": "#160406",
  "/orders": "#130104",
  "/account": "#130104",
  "/login": "#130104",
  "/register": "#130104",
  "/partners": "#0E1122",
} as const satisfies Record<string, string>;

/**
 * Longest-prefix match, so `/shop/گوشی-…` is a product page and `/shop` is the listing — and `/admin`,
 * `/api` and anything unlisted get `null`, because the operations surface is not a shopper page and the
 * owner's decision was about shoppers.
 */
export function interiorGround(pathname: string): string | null {
  if (pathname === "/") return null;
  let best: { prefix: string; color: string } | null = null;
  for (const [prefix, color] of Object.entries(INTERIOR_GROUNDS)) {
    if (pathname !== prefix && !pathname.startsWith(`${prefix}/`)) continue;
    if (!best || prefix.length > best.prefix.length) best = { prefix, color };
  }
  return best?.color ?? null;
}

/**
 * Where each stage begins, as a fraction of scrollable height.
 *
 * With no layout given, stages are placed at their anchor section's position in the document order —
 * even enough to be honest, and stable under test. `useScrollProgress` passes real section offsets so
 * the boundaries land where the shopper actually sees the section, which is FR-002: the shift must read
 * as belonging to the page's structure, not as an independent animation.
 */
export function stageBoundaries(sectionOffsets?: readonly number[]): readonly number[] {
  return PROGRESSION.map((stage) => {
    const index = HOMEPAGE_SECTIONS.indexOf(stage.anchor);
    if (sectionOffsets && sectionOffsets.length === HOMEPAGE_SECTIONS.length) {
      return clamp01(sectionOffsets[index] ?? 0);
    }
    return clamp01(index / (HOMEPAGE_SECTIONS.length - 1));
  });
}

export function toneAt(progress: number, boundaries: readonly number[] = stageBoundaries()): string {
  const p = clamp01(progress);
  const bounds = boundaries.length === PROGRESSION.length ? boundaries : stageBoundaries();
  let segment = 0;
  for (let i = 1; i < bounds.length; i += 1) {
    if (p >= (bounds[i] ?? 1)) segment = i;
  }
  const from = PROGRESSION[segment]!;
  const to = PROGRESSION[Math.min(segment + 1, PROGRESSION.length - 1)]!;
  if (from === to) return from.color;

  const span = (bounds[segment + 1] ?? 1) - (bounds[segment] ?? 0);
  const local = span <= 0 ? 0 : clamp01((p - (bounds[segment] ?? 0)) / span);
  const [r1, g1, b1] = toRgb(from.color);
  const [r2, g2, b2] = toRgb(to.color);
  // Interpolated byte-by-byte in sRGB, not in HSL, and no colour library. That is a real compromise now
  // that the stages differ in hue: on the two long legs (wine → ink, ink → ember) the midpoint passes
  // through a low-chroma plum-brown the eye reads as "between rooms" rather than as a colour of its own.
  // Measured across the 500-step sweep the worst intermediate stays inside `LEGIBILITY_BAND` and holds
  // 5.59:1 against the dimmest text on the page, so the blend is neither illegible nor band-breaking —
  // it is just not a hue a designer would choose. It is never *held* long enough to be one: the legs span
  // three sections each, and the shopper is moving.
  return toHex(r1 + (r2 - r1) * local, g1 + (g2 - g1) * local, b1 + (b2 - b1) * local);
}

/**
 * FR-020: the reduced-motion page gets distinct settled tones per region with no animated travel.
 * Same stages, same count — the shopper cannot tell they received a shorter progression (FR-021).
 */
export function reducedMotionTone(progress: number, boundaries: readonly number[] = stageBoundaries()): string {
  const p = clamp01(progress);
  const bounds = boundaries.length === PROGRESSION.length ? boundaries : stageBoundaries();
  let segment = 0;
  for (let i = 1; i < bounds.length; i += 1) {
    if (p >= (bounds[i] ?? 1)) segment = i;
  }
  return PROGRESSION[segment]!.color;
}
